# Generated by Django 5.1.3 on 2025-04-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_habit_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='target_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
