# Generated by Django 5.1.3 on 2025-04-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_habit_target_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='minutes_done',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
