# Generated by Django 5.1.3 on 2025-04-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_habitlog_minutes_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='note',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
