# Generated by Django 5.1.3 on 2025-04-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_friendrequest_is_accepted_alter_habitlog_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitlog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together=set(),
        ),
    ]
